searchSpaceFile: ../nni_search_spaces/search_space_snn_weight_transfer.json
trialCommand: python3 ../src/pytorch_snntorch/nni_snn_weight_transfer.py --no-lightweight
trialConcurrency: 1
trialCodeDirectory: .           # The path of trial code. By default it's ".", which means the same directory of this config file.
maxExperimentDuration: 18h       # Stop generating trials after 4 hour.
tuner:
  name: Anneal
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: false